global:
  scrape_interval: 10s

rule_files:
  - /etc/prometheus/rules.d/*.rules

scrape_configs:
  - job_name: 'prometheus'
    target_groups:
      - targets: ['localhost:9090']
    metrics_path: '/prometheus/metrics'

  - job_name: 'node-exporter'
    target_groups:
      - targets: ['localhost:9100']
